const ERAS=['전체',...new Set(CHAPTERS.map(x=>x.era))];
let selectedEra='전체',current=null,quiz=null;
const state=JSON.parse(localStorage.getItem('hanguksa40-state')||'{}');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function getS(id){return state[id]||(state[id]={revealed:[],correct:0,attempt:0,last:0})}
function save(){localStorage.setItem('hanguksa40-state',JSON.stringify(state));updateTotal()}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1600)}
function updateTotal(){let r=0,c=0,ok=0,a=0;CHAPTERS.forEach(x=>{const s=getS(x.id);r+=s.revealed.length;c+=s.revealed.length===x.notes.length;ok+=s.correct;a+=s.attempt});const max=CHAPTERS.reduce((n,x)=>n+x.notes.length,0);const pct=Math.round(r/max*100);$('#totalBar').style.width=pct+'%';$('#totalText').textContent=pct+'%';$('#statComplete').textContent=c+' / 40';$('#statCorrect').textContent=ok+(a?' / '+a:'');$('#statReveal').textContent=r+' / '+max;$('#statRate').textContent=pct+'%'}
function renderChips(){const box=$('#chips');box.innerHTML=ERAS.map(e=>`<button class="chip ${e===selectedEra?'on':''}" data-era="${e}">${e}</button>`).join('');box.onclick=e=>{if(!e.target.dataset.era)return;selectedEra=e.target.dataset.era;renderChips();renderGrid()}}
function renderGrid(){const q=$('#search').value.trim().toLowerCase();const list=CHAPTERS.filter(x=>(selectedEra==='전체'||x.era===selectedEra)&&(!q||x.title.toLowerCase().includes(q)||x.notes.some(n=>(n.term+n.desc).toLowerCase().includes(q))));$('#countLabel').textContent=list.length+'개';$('#grid').innerHTML=list.map(x=>{const s=getS(x.id),p=Math.round(s.revealed.length/x.notes.length*100),done=p===100;return `<article class="card" data-id="${x.id}"><div><div class="num">PART ${String(x.id).padStart(2,'0')} ${done?'<span class="doneMark">✓ 완료</span>':''}</div><h3>${x.title}</h3><div class="tag">${x.era} · 빈칸 ${x.notes.length}개</div></div><div class="cardProg"><i style="width:${p}%"></i></div></article>`}).join('')||'<div class="empty">검색 결과가 없습니다.</div>';$('#grid').onclick=e=>{const c=e.target.closest('.card');if(c)openChapter(+c.dataset.id)}}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('on',v.id===id));$$('.nav').forEach(n=>n.classList.toggle('on',n.dataset.view===id));if(id==='statsView')renderStats();scrollTo(0,0)}
function openChapter(id){current=CHAPTERS.find(x=>x.id===id);const s=getS(id);s.last=Date.now();save();$('#detailTitle').textContent=`${String(id).padStart(2,'0')}. ${current.title}`;$('#detailMeta').textContent=`${current.era} · 노션 핵심 + 기출형 회상`;$('#paperTitle').textContent=current.title;$('#quizArea').innerHTML='';renderNotes();showView('detail')}
function renderNotes(){const s=getS(current.id);$('#notes').innerHTML=current.notes.map((n,i)=>`<div class="note"><div class="bullet">${i+1}</div><div class="noteBody"><div class="clue">${n.desc}</div><button class="blank ${s.revealed.includes(i)?'revealed':''}" data-i="${i}">${s.revealed.includes(i)?n.term:''}</button></div></div>`).join('');$('#notes').onclick=e=>{const b=e.target.closest('.blank');if(!b)return;const i=+b.dataset.i;if(!s.revealed.includes(i)){s.revealed.push(i);save();renderNotes();if(s.revealed.length===current.notes.length)toast('도화지 복원 완료! 문제를 풀 수 있어요.')}};$('#startQuiz').disabled=s.revealed.length!==current.notes.length}
function makeQuiz(){const idx=Math.floor(Math.random()*current.notes.length),target=current.notes[idx];let pool=[...new Set(CHAPTERS.flatMap(x=>x.notes.map(n=>n.term)).filter(t=>t!==target.term))];pool.sort(()=>Math.random()-.5);let opts=[target.term,...pool.slice(0,3)].sort(()=>Math.random()-.5);quiz={target,opts,answered:false};$('#quizArea').innerHTML=`<div class="quizBox"><span class="badge">69~78회 핵심 포인트 기반</span><h3>다음 설명에 해당하는 핵심어는?</h3><p>${target.desc}</p><div class="opts">${opts.map(o=>`<button class="opt" data-o="${o}">${o}</button>`).join('')}</div><div id="explain"></div></div>`;$('#quizArea').onclick=e=>{const b=e.target.closest('.opt');if(!b||quiz.answered)return;quiz.answered=true;const right=b.dataset.o===target.term, s=getS(current.id);s.attempt++;if(right)s.correct++;save();$$('.opt').forEach(x=>{if(x.dataset.o===target.term)x.classList.add('good');else if(x===b)x.classList.add('bad')});$('#explain').innerHTML=`<div class="explain"><b>${right?'정답입니다!':'오답입니다.'}</b><br><strong>${target.term}</strong> — ${target.desc}<br><button class="btn" style="margin-top:10px" onclick="makeQuiz()">다른 문제</button>${right?'':` <button class="btn" style="margin-top:10px" onclick="focusBlank('${target.term}')">판서로 복귀</button>`}</div>`}}
function focusBlank(term){const i=current.notes.findIndex(n=>n.term===term);getS(current.id).revealed=getS(current.id).revealed.filter(x=>x!==i);save();renderNotes();$('#quizArea').innerHTML='';setTimeout(()=>$$('.blank')[i].scrollIntoView({behavior:'smooth',block:'center'}),30);toast('틀린 개념을 다시 가렸습니다.')}
function renderStats(){updateTotal();const rec=CHAPTERS.map(x=>({x,s:getS(x.id)})).filter(o=>o.s.last).sort((a,b)=>b.s.last-a.s.last).slice(0,8);$('#recent').innerHTML=rec.length?rec.map(o=>`<div class="row"><span>${String(o.x.id).padStart(2,'0')}. ${o.x.title}</span><b>${o.s.revealed.length}/${o.x.notes.length}</b></div>`).join(''):'<div class="empty">아직 학습 기록이 없습니다.</div>'}
$('#search').oninput=renderGrid;$('#back').onclick=()=>{renderGrid();showView('home')};$('#reset').onclick=()=>{getS(current.id).revealed=[];save();renderNotes();$('#quizArea').innerHTML='';toast('빈칸을 다시 가렸습니다.')};$('#revealAll').onclick=()=>{getS(current.id).revealed=current.notes.map((_,i)=>i);save();renderNotes();toast('전체 판서를 복원했습니다.')};$('#startQuiz').onclick=makeQuiz;$('#continueBtn').onclick=()=>{const rec=CHAPTERS.map(x=>({x,s:getS(x.id)})).sort((a,b)=>b.s.last-a.s.last)[0];openChapter(rec&&rec.s.last?rec.x.id:1)};$$('.nav').forEach(n=>n.onclick=()=>showView(n.dataset.view));renderChips();renderGrid();updateTotal();